---
name: kovo
image: kovospace-frontend

# Nastavenie domény
containerPort: 3000
host: kovo.space

# Pripojenie na postgres databázu
externalServices:
  postgres:
    address: 172.17.0.1 # docker0 gateway — must be an IP, not a hostname
    port: 5432

# Volumes
persistence:
  media:
    size: 10Gi
    mountPath: /app/public/media
  images:
    size: 10Gi
    mountPath: /app/public/images
  icons:
    size: 1Gi
    mountPath: /app/public/icons

env:
  # DATABASE_URI: "" # Moved into vault
  # PAYLOAD_SECRET: "" # Moved into vault
  NEXT_PUBLIC_SERVER_URL: https://kovo.space
  ALLOWED_ORIGINS: https://www.kovo.space,https://kovo.space

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    memory: 512Mi