apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: kovo-old
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:

  project: applications

  sources:

    ### Základné Kubernetes resources
    - repoURL: git@github.com:Kovospace/kovostack-helm-charts.git
      targetRevision: chart-app-1.7.0
      path: charts/app
      helm:
        valueFiles:
          - $values/applications/kovo-old/values.yaml
          - $values/versions/kovo-old.yaml

    ### Pointer na referencovaý values.yaml
    - repoURL: git@github.com:Kovospace/kovostack-infra-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kovo-old

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false