apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: new-tab-links-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:

  project: applications

  sources:

    - repoURL: git@github.com:Kovospace/kovostack-helm-charts.git
      targetRevision: chart-app-1.4.1
      path: charts/app
      helm:
        valueFiles:
          - $values/applications/new-tab-links-backend/values.yaml
          - $values/versions/new-tab-links-backend.yaml
          - $values/versions/new-tab-links-backend-init.yaml

    - repoURL: git@github.com:Kovospace/kovostack-infra-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: new-tab-links-backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false