---
name: paster-backend
image: paster-backend

# Nastavenie domény
containerPort: 3000
host: api.paster.cloud

# Pripojenie na postgres databázu
externalServices:
  postgres:
    address: 172.17.0.1 # docker0 gateway — must be an IP, not a hostname
    port: 5432

# Volumes
persistence:
  files:
    size: 10Gi
    mountPath: /app/uploads/files
  temp:
    size: 10Gi
    mountPath: /app/uploads/temp

env:
  # SECRET_KEY: ${SECRET_KEY} # presunuté do vault
  # SPRING_DATASOURCE_USER: ${DB_USER} # presunuté do vault
  # SPRING_DATASOURCE_PASS: ${DB_USER_PASSWORD} # presunuté do vault
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paster
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

resources:
  requests:
    cpu: 250m
    memory: 128Mi
  limits:
    memory: 512Mi