---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.gateway.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.gateway.name }}
  ports:
    - name: http
      port: {{ .Values.gateway.port }}
      targetPort: http
